name: Build and push to ECR
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-southeast-1

      - name: Log in to Amazon ECR
        id: ecr-login
        uses: aws-actions/amazon-ecr-login@v1

      - name: Build Docker image
        run: |
          docker build -t journaling-app:latest .

      - name: Tag Docker image
        run: |
          IMAGE_URI=${{ secrets.AWS_ECR_REPOSITORY_URI }}
          docker tag journaling-app:latest $IMAGE_URI:latest

      - name: Push Docker image to ECR
        run: |
          IMAGE_URI=${{ secrets.AWS_ECR_REPOSITORY_URI }}
          docker push $IMAGE_URI:latest